window = {
	"name" : "selectcharacterwindow",
	"x" : 0, "y" : 0,
	"width" : SCREEN_WIDTH,	"height" : SCREEN_HEIGHT,
	"children" : (
		{
			"name" : "BackGround",
			"type" : "expanded_image",
			"x" : 0, "y" : 0,
			"x_scale" : float(SCREEN_WIDTH) / 1366.0,
			"y_scale" : float(SCREEN_HEIGHT) / 768.0,
			"image" : "sistimata/interface/characterwindow/background.tga",
			"children" : (
				{
					"name" : "board_main",
					"type" : "window",
					"x" : -300, "y" : 20,
					"width" : 352, "height" : 457,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"children" :(
						{
							"name" : "board",
							"type" : "image",
							"x" : 0, "y" : 0,
							"image" : "sistimata/interface/characterwindow/select/board.tga",
							"children" : (
								{
									"name" : "name_slotbar",
									"type" : "image",
									"x" : 45, "y" : -115,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"image" : "sistimata/interface/characterwindow/select/slotbar.tga",
									"children" : (
										{
											"name" : "name",
											"type" : "text",
											"x" : 0, "y" : 0,
											"all_align" : True,
										},
									),
								},
								{
									"name" : "level_slotbar",
									"type" : "image",
									"x" : 45, "y" : -73,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"image" : "sistimata/interface/characterwindow/select/slotbar.tga",
									"children" : (
										{
											"name" : "level",
											"type" : "text",
											"x" : 0, "y" : 0,
											"all_align" : True,
										},
									),
								},
								{
									"name" : "guild_slotbar",
									"type" : "image",
									"x" : 45, "y" : -28,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"image" : "sistimata/interface/characterwindow/select/slotbar.tga",
									"children" : (
										{
											"name" : "guild",
											"type" : "text",
											"x" : 0, "y" : 0,
											"all_align" : True,
										},
									),
								},
								{
									"name" : "empire_slotbar",
									"type" : "image",
									"x" : 45, "y" : 11,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"image" : "sistimata/interface/characterwindow/select/slotbar.tga",
									"children" : (
										{
											"name" : "empire",
											"type" : "text",
											"x" : 0, "y" : 0,
											"all_align" : True,
										},
									),
								},
								{
									"name" : "playtime_slotbar",
									"type" : "image",
									"x" : 45, "y" : 52,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"image" : "sistimata/interface/characterwindow/select/slotbar.tga",
									"children" : (
										{
											"name" : "playtime",
											"type" : "text",
											"x" : 0, "y" : 0,
											"all_align" : True,
										},
									),
								},
								{
									"name" : "delete_button",
									"type" : "button",
									"x" : 10, "y" : 100,
									"vertical_align" : "center",
									"horizontal_align" : "center",
									"default_image" : "sistimata/interface/characterwindow/select/delete_0.tga",
									"over_image" : "sistimata/interface/characterwindow/select/delete_1.tga",
									"down_image" : "sistimata/interface/characterwindow/select/delete_2.tga",
								},
							),
						},
						{
							"name" : "select_button",
							"type" : "button",
							"x" : 10, "y" : 120,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"default_image" : "sistimata/interface/characterwindow/select/select_0.tga",
							"over_image" : "sistimata/interface/characterwindow/select/select_1.tga",
							"down_image" : "sistimata/interface/characterwindow/select/select_2.tga",
						},
						{
							"name" : "create_button",
							"type" : "button",
							"x" : 10, "y" : 120,
							"vertical_align" : "center",
							"horizontal_align" : "center",
							"default_image" : "sistimata/interface/characterwindow/select/create_0.tga",
							"over_image" : "sistimata/interface/characterwindow/select/create_1.tga",
							"down_image" : "sistimata/interface/characterwindow/select/create_2.tga",
						},
					),
				},
				{
					"name" : "left_button",
					"type" : "button",
					"x" : -350, "y" : 230,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"default_image" : "sistimata/interface/characterwindow/select/left_0.tga",
					"over_image" : "sistimata/interface/characterwindow/select/left_1.tga",
					"down_image" : "sistimata/interface/characterwindow/select/left_2.tga",
				},
				{
					"name" : "right_button",
					"type" : "button",
					"x" : -240, "y" : 230,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"default_image" : "sistimata/interface/characterwindow/select/right_0.tga",
					"over_image" : "sistimata/interface/characterwindow/select/right_1.tga",
					"down_image" : "sistimata/interface/characterwindow/select/right_2.tga",
				},
				{
					"name" : "exit_button",
					"type" : "button",
					"x" : SCREEN_WIDTH - 115, "y" : 10,
					"default_image" : "sistimata/interface/loginwindow/exit_0.tga",
					"over_image" :  "sistimata/interface/loginwindow/exit_1.tga",
					"down_image" : "sistimata/interface/loginwindow/exit_2.tga",
				},
			),
		},
	),
}
