BASE_PATH = "sistimata/images/kingdom/"
BTN_PATH = BASE_PATH + "btn/"

height = 0
if SCREEN_HEIGHT <= 1000:
	height = -120

window = {
	"name" : "SelectEmpireWindow",
	"x" : 0, "y" : 0, "width" : SCREEN_WIDTH, "height" : SCREEN_HEIGHT,
	"style" : ("float",),
	"children" :
	(
		{
			"name" : "background", "type" : "image",
			"x" : SCREEN_WIDTH / 2 - 1920 / 2, "y" : 0 + height,
			"image" : BASE_PATH + "background.tga",
		},
		{
			"name" : "content_01", "type" : "image",
			"vertical_align" : "center", "horizontal_align" : "center",
			"x" : -396 + 256 / 2, "y" : 0,
			"image" : BASE_PATH + "content.tga",
			"children" :
			(
				{
					"name" : "kingdom_name_01", "type" : "image",
					"horizontal_align" : "center",
					"x" : 5, "y" : 50,
					"image" : BASE_PATH + "img_text_red.tga",
				},
				{
					"name" : "kingdom_01", "type" : "image",
					"horizontal_align" : "center",
					"x" : 5, "y" : 80,
					"image" : BASE_PATH + "img_flag_red.tga",
				},
				{
					"name" : "text_kingdom_01_01", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*0,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_01_02", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*1,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_01_03", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*2,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_01_04", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*3,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_01_05", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*4,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "btn_select_01", "type" : "button",
					"x" : 5, "y" : 110,
					"horizontal_align" : "center",
					"vertical_align" : "bottom",
					"default_image" : BTN_PATH + "btn_select_normal.tga",
					"over_image" : BTN_PATH + "btn_select_hover.tga",
					"down_image" : BTN_PATH + "btn_select_active.tga",
				},
			),
		},
		{
			"name" : "content_02", "type" : "image",
			"vertical_align" : "center", "horizontal_align" : "center",
			"x" : 0, "y" : 0,
			"image" : BASE_PATH + "content.tga",
			"children" :
			(
				{
					"name" : "kingdom_name_02", "type" : "image",
					"horizontal_align" : "center",
					"x" : 5, "y" : 50,
					"image" : BASE_PATH + "img_text_yellow.tga",
				},
				{
					"name" : "kingdom_02", "type" : "image",
					"horizontal_align" : "center",
					"x" : 5, "y" : 80,
					"image" : BASE_PATH + "img_flag_yellow.tga",
				},
				{
					"name" : "text_kingdom_02_01", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*0,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_02_02", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*1,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_02_03", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*2,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_02_04", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*3,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_02_05", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*4,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "btn_select_02", "type" : "button",
					"x" : 5, "y" : 110,
					"horizontal_align" : "center",
					"vertical_align" : "bottom",
					"default_image" : BTN_PATH + "btn_select_normal.tga",
					"over_image" : BTN_PATH + "btn_select_hover.tga",
					"down_image" : BTN_PATH + "btn_select_active.tga",
				},
			),
		},
		{
			"name" : "exit_button", "type" : "button",
			"x" : 5, "y" : 148,
			"horizontal_align" : "center",
			"vertical_align" : "bottom",
			"default_image" : BTN_PATH + "exit_0.tga",
			"over_image" : BTN_PATH + "exit_1.tga",
			"down_image" : BTN_PATH + "exit_2.tga",
		},
		{
			"name" : "content_03", "type" : "image",
			"vertical_align" : "center", "horizontal_align" : "center",
			"x" : 144 + 256 / 2, "y" : 0,
			"image" : BASE_PATH + "content.tga",
			"children" :
			(
				{
					"name" : "kingdom_name_03", "type" : "image",
					"horizontal_align" : "center",
					"x" : 5, "y" : 50,
					"image" : BASE_PATH + "img_text_blue.tga",
				},
				{
					"name" : "kingdom_03", "type" : "image",
					"horizontal_align" : "center",
					"x" : 5, "y" : 80,
					"image" : BASE_PATH + "img_flag_blue.tga",
				},
				{
					"name" : "text_kingdom_03_01", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*0,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_03_02", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*1,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_03_03", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*2,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_03_04", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*3,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "text_kingdom_03_05", "type" : "text",
					"x" : 223 / 2 + 22, "y" : 155+18*4,
					"text_horizontal_align" : "center",
					"fontname" : "Tahoma:13",
					"color" : 0xffCECECE,
					"text" : "DEFAULT TEXT",
				},
				{
					"name" : "btn_select_03", "type" : "button",
					"x" : 5, "y" : 110,
					"horizontal_align" : "center",
					"vertical_align" : "bottom",
					"default_image" : BTN_PATH + "btn_select_normal.tga",
					"over_image" : BTN_PATH + "btn_select_hover.tga",
					"down_image" : BTN_PATH + "btn_select_active.tga",
				},
			),
		},
	),
}
