import app
window = {
	"sytle" : ("movable",),
	"x" : 0, "y" : 0,
	"width" : SCREEN_WIDTH,
	"height" : SCREEN_HEIGHT,
	"children" : (
		{
			"name" : "background", 
			"type" : "expanded_image",
			"x" : 0, "y" : 0,
			"x_scale" : float(SCREEN_WIDTH) / 1366.0,
			"y_scale" : float(SCREEN_HEIGHT) / 768.0,
			"image" : "sistimata/interface/loginwindow/background.tga",
			"children" : (
				{
					"name" : "board_main",
					"type" : "window",
					"x" : 0, "y" : 0,
					"width" : 352, "height" : 290,
					"vertical_align" : "center",
					"horizontal_align" : "center",
					"children" :(
						{
							"name" : "board",
							"type" : "image",
							"x" : 0, "y" : 0,
							"image" : "sistimata/interface/loginwindow/board.tga",
							"children" : (
								{
									"name" : "id_slotbar",
									"type" : "image",
									"x" : 45, "y" : -33,
									"horizontal_align" : "center",
									"vertical_align" : "center",
									"image" : "sistimata/interface/loginwindow/slotbar.tga",
									"children" : (
										{
											"name" : "id",
											"type" : "editline",
											"x" : 12, "y" : 10,
											"width" : 200, "height" : 16,
											"color" : 0xffc8aa80,
											"input_limit": 16,
										},
									),
								},
								{
									"name" : "pwd_slotbar",
									"type" : "image",
									"x" : 45, "y" : 7,
									"horizontal_align" : "center",
									"vertical_align" : "center",
									"image" : "sistimata/interface/loginwindow/slotbar.tga",
									"children" : (
										{
											"name" : "pwd",
											"type" : "editline",
											"x" : 12, "y" : 10,
											"width" : 200, "height" : 16,
											"color" : 0xffc8aa80,
											"input_limit": 16,
											"secret_flag": 1,
										},
									),
								},
								{
									"name" : "pin_slotbar",
									"type" : "image",
									"x" : 45, "y" : 46,
									"horizontal_align" : "center",
									"vertical_align" : "center",
									"image" : "sistimata/interface/loginwindow/slotbar.tga",
									"children" : (
										{
											"name" : "pin",
											"type" : "editline",
											"x" : 12, "y" : 10,
											"width" : 200, "height" : 16,
											"color" : 0xffc8aa80,
											"input_limit": 7,
											"secret_flag": 0,
										},
									),
								},
							),
						},
						{
							"name" : "login_button",
							"type" : "button",
							"x" : 0, "y" : 79,
							"horizontal_align" : "center",
							"vertical_align" : "center",
							"default_image" : "sistimata/interface/loginwindow/login_0.tga", 
							"over_image" : "sistimata/interface/loginwindow/login_1.tga",
							"down_image" : "sistimata/interface/loginwindow/login_2.tga",
						},
					),
				},
								{
					"name" : "account_board",
					"type" : "image",
					"x" : 0, "y" : 215,
					"horizontal_align" : "center",
					"vertical_align" : "center",
					"image" : "sistimata/interface/loginwindow/account/board.tga",
					"children" : (
						{
							"name" : "account_0_image",
							"type" : "image",
							"x" : 40, "y" : 35,
							"image" : "sistimata/interface/loginwindow/account/slotbar.tga",
							"children" : (
								{
									"name" : "account_0_text",
									"type" : "text",
									"x" : 0, "y" : -1,
									"all_align" : True,
								},
							),
						},
						{
							"name" : "save_button_0",
							"type" : "button",
							"x" : 165, "y" : 36,
							"default_image" : "sistimata/interface/loginwindow/account/save_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/save_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/save_2.tga",
						},
						{
							"name" : "load_button_0",
							"type" : "button",
							"x" : 165, "y" : 36,
							"default_image" : "sistimata/interface/loginwindow/account/load_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/load_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/load_2.tga",
						},
						{
							"name" : "delete_button_0",
							"type" : "button",
							"x" : 295, "y" : 36,
							"default_image" : "sistimata/interface/loginwindow/account/delete_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/delete_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/delete_2.tga",
						},
						{
							"name" : "account_1_image",
							"type" : "image",
							"x" : 40, "y" : 70,
							"image" : "sistimata/interface/loginwindow/account/slotbar.tga",
							"children" : (
								{
									"name" : "account_1_text",
									"type" : "text",
									"x" : 0, "y" : -1,
									"all_align" : True,
								},
							),
						},
						{
							"name" : "save_button_1",
							"type" : "button",
							"x" : 165, "y" : 70,
							"default_image" : "sistimata/interface/loginwindow/account/save_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/save_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/save_2.tga",
						},
						{
							"name" : "load_button_1",
							"type" : "button",
							"x" : 165, "y" : 70,
							"default_image" : "sistimata/interface/loginwindow/account/load_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/load_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/load_2.tga",
						},
						{
							"name" : "delete_button_1",
							"type" : "button",
							"x" : 295, "y" : 70,
							"default_image" : "sistimata/interface/loginwindow/account/delete_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/delete_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/delete_2.tga",
						},
						{
							"name" : "account_2_image",
							"type" : "image",
							"x" : 40, "y" : 104,
							"image" : "sistimata/interface/loginwindow/account/slotbar.tga",
							"children" : (
								{
									"name" : "account_2_text",
									"type" : "text",
									"x" : 0, "y" : -1,
									"all_align" : True,
								},
							),
						},
						{
							"name" : "save_button_2",
							"type" : "button",
							"x" : 165, "y" : 104,
							"default_image" : "sistimata/interface/loginwindow/account/save_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/save_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/save_2.tga",
						},
						{
							"name" : "load_button_2",
							"type" : "button",
							"x" : 165, "y" : 104,
							"default_image" : "sistimata/interface/loginwindow/account/load_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/load_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/load_2.tga",
						},
						{
							"name" : "delete_button_2",
							"type" : "button",
							"x" : 295, "y" : 104,
							"default_image" : "sistimata/interface/loginwindow/account/delete_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/delete_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/delete_2.tga",
						},
						{
							"name" : "account_3_image",
							"type" : "image",
							"x" : 40, "y" : 138,
							"image" : "sistimata/interface/loginwindow/account/slotbar.tga",
							"children" : (
								{
									"name" : "account_3_text",
									"type" : "text",
									"x" : 0, "y" : -1,
									"all_align" : True,
								},
							),
						},
						{
							"name" : "save_button_3",
							"type" : "button",
							"x" : 165, "y" : 138,
							"default_image" : "sistimata/interface/loginwindow/account/save_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/save_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/save_2.tga",
						},
						{
							"name" : "load_button_3",
							"type" : "button",
							"x" : 165, "y" : 138,
							"default_image" : "sistimata/interface/loginwindow/account/load_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/load_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/load_2.tga",
						},
						{
							"name" : "delete_button_3",
							"type" : "button",
							"x" : 295, "y" : 138,
							"default_image" : "sistimata/interface/loginwindow/account/delete_0.tga",
							"over_image" :  "sistimata/interface/loginwindow/account/delete_1.tga",
							"down_image" : "sistimata/interface/loginwindow/account/delete_2.tga",
						},
					),
				},
				{
					"name" : "ch1",
					"type" : "radio_button",
					"x" : -200, "y" : -75,
					"horizontal_align" : "center",
					"vertical_align" : "center",
					"default_image" : "sistimata/interface/loginwindow/channel/ch1_0.tga",
					"over_image" : "sistimata/interface/loginwindow/channel/ch1_1.tga",
					"down_image" : "sistimata/interface/loginwindow/channel/ch1_2.tga",
				},
				{
					"name" : "ch2",
					"type" : "radio_button",
					"x" : -200, "y" : -20,
					"horizontal_align" : "center",
					"vertical_align" : "center",
					"default_image" : "sistimata/interface/loginwindow/channel/ch2_0.tga",
					"over_image" : "sistimata/interface/loginwindow/channel/ch2_1.tga",
					"down_image" : "sistimata/interface/loginwindow/channel/ch2_2.tga",
				},
				{
					"name" : "ch3",
					"type" : "radio_button",
					"x" : -200, "y" : 35,
					"horizontal_align" : "center",
					"vertical_align" : "center",
					"default_image" : "sistimata/interface/loginwindow/channel/ch3_0.tga",
					"over_image" : "sistimata/interface/loginwindow/channel/ch3_1.tga",
					"down_image" : "sistimata/interface/loginwindow/channel/ch3_2.tga",
				},
				{
					"name" : "ch4",
					"type" : "radio_button",
					"x" : 200, "y" : -75,
					"horizontal_align" : "center",
					"vertical_align" : "center",
					"default_image" : "sistimata/interface/loginwindow/channel/ch4_0.tga",
					"over_image" : "sistimata/interface/loginwindow/channel/ch4_1.tga",
					"down_image" : "sistimata/interface/loginwindow/channel/ch4_2.tga",
				},
				{
					"name" : "ch5",
					"type" : "radio_button",
					"x" : 200, "y" : -20,
					"horizontal_align" : "center",
					"vertical_align" : "center",
					"default_image" : "sistimata/interface/loginwindow/channel/ch5_0.tga",
					"over_image" : "sistimata/interface/loginwindow/channel/ch5_1.tga",
					"down_image" : "sistimata/interface/loginwindow/channel/ch5_2.tga",
				},
				{
					"name" : "ch6",
					"type" : "radio_button",
					"x" : 200, "y" : 35,
					"horizontal_align" : "center",
					"vertical_align" : "center",
					"default_image" : "sistimata/interface/loginwindow/channel/ch6_0.tga",
					"over_image" : "sistimata/interface/loginwindow/channel/ch6_1.tga",
					"down_image" : "sistimata/interface/loginwindow/channel/ch6_2.tga",
				},
				{
					"name" : "exit_button",
					"type" : "button",
					"x" : SCREEN_WIDTH - 115, "y" : 10,
					"default_image" : "sistimata/interface/loginwindow/exit_0.tga",
					"over_image" :  "sistimata/interface/loginwindow/exit_1.tga",
					"down_image" : "sistimata/interface/loginwindow/exit_2.tga",
				},
			),
		},
	),
}